[project]
name = "farsight"
version = "0.1.0"
dependencies = ["requests==2.*"]

[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.10.4"]
build-backend = "setuptools.build_meta"
