[project]
name = "farsight"
version = "0.2.0"
dependencies = ["requests~=2.15"]

[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.10.4"]
build-backend = "setuptools.build_meta"
